Squashed '.logistic/' changes from e9eaf49..42a2fba
42a2fba Merge feature/nix-shallow-dune-pkg into master.
cc8a49e Provide dune preview (with dune pkg) in shallow nix shell
b0790b3 Merge feature/extra-overlay-with-pkgs into master.
e91260d Bump the OCaml repos
38fa796 Allow accessing the global pkgs set from the extra OCaml overlay
4a8a8ee Opt-in cross compilation.
26ff6c3 Simplify dune pkg CI flow.
8c34ad6 CI: Handle Alpine packages.
fe4732d Merge feature/ignore-routine-crdt-tests into master.
6f7cfdd Factor dune workspace.
210e6be Adapt logistic to latest front
de17ced dune-builder: Fix opam publishing.
a0d6a43 Bump dune builder.
ada790e dune-builder: Fix opam publishing.
46bd8d7 Merge feature/ocamlformat-0.27.0 into master.
0dbc542 Make acid-jsoo depend on the overriden acid-lwt
fc43ef0 Add missing bumps
f375088 Add shell.nix
3a7e772 Upgrade to ocamlformat 0.27.0.
56ea0b7 Merge feature/dune-pkg into master.
3f5e16b README: Document `dune pkg` flow.
2120095 dune_sak: Document CLI.
b6d6d31 Merge feature/remove-gitignore into master.
75d2122 nix flake update opam-nix opam-repository routine-opam-repository
227585d Add missing "follows"
edc8205 Get rid of gitignore as it breaks on recent nixpkgs versions
59de096 Format generated dune file.
2e84398 dune_sak: Clean dependencies.
f9f684e Apply 3 suggestion(s) to 2 file(s)
d1536e5 Don't dynamically generate Opam files.
7069e24 Merge master into feature/dune-pkg.
1092675 Fix dune-pkg helpers.
4c587fd Bump dune builder.
b8e8b37 Merge branch master into feature/dune-pkg.
5071ab0 Add dune-pkg helpers.
88dc5a1 Install bash in dune builder.
f495492 Don't try to enforce dune version, go with the flow.
11adf61 Install autoconf in dune builder.
58510e2 Merge feature/upgrade-alpine-21 into master.
0a706e9 Upgrade to Alpine 3.21.0
fec0631 dune-builder: Add OpenSSH, remove S3.
ff598c7 Merge feature/update-opam-stuff into master.
71ba27b Update Opam stuff
d7f6aef Merge feature/opam-dune-lint into master.
5072765 Format
a0e95bc Add opam-dune-lint to CI and extdeps
1133701 nix flake update nixpkgs routine-opam-repository
02fed76 Ensure reproducibility of the `dune` version.
7648f70 Merge feature/ocamlformat-add-break-infix into master.
d33b484 Add `break-infix=fit-or-vertical` to ocamlformat
7d97ad1 CI: Show packaged image name.
3e8908a Merge feature/document-overriding-shell-nix into master.
5a28948 Document overriding the shell.nix
9633bb3 Merge feature/allow-passing-overlays into master.
f7dc608 Allow passing overlays to the Nix shell
7ab8dec Merge feature/add-missing-overlays into master.
e4dbe4f nixpkgs-fmt
fcdb13e Add missing overlays
5c3d7c1 Merge feature/simpler-routine-run into master.
805aeeb Simplify the inputs of routine_run
ddbc8aa Merge feature/update-stuff into master.
f9298a9 Update the flake lock
82a4667 Merge feature/swift-support into master.
47878ea Add Swift support
d324662 Merge feature/make-opam-source-filter-overridable into master.
7874d18 nix flake update opam-nix
8bdae80 Make opam source filter overridable
68735fa Bump opam.
df56d88 Merge feature/update-opam-repositories-2024-12-03 into master.
f1513b6 Update opam repositories
ad1804d Add dune CI.
7e16d2e Add dune builder.

git-subtree-dir: .logistic
git-subtree-split: 42a2fba6bdcd4dc32ff55a8f3d56a343ca4be395

diff --git a/ci/Makefile b/ci/Makefile
--- a/ci/Makefile
+++ b/ci/Makefile
@@ -20,7 +20,12 @@ build:
 	$(DUNE) subst
 	$(DUNE) build --profile release $(if ${DUNE_PACKAGES},--only-packages="${DUNE_PACKAGES}") --ignore-promoted-rules @install
 
+# `opam-dune-lint` does not correctly honor the global switch set via OPAMSWITCH env var, so as a workaround, we symlink `_opam`
+# See https://discuss.ocaml.org/t/opam-dune-lint-fails-on-bare-opam-initialization/16045/2
 lint:
+	ln -s /root/_opam _opam
+	opam exec -- opam-dune-lint
+	rm _opam
 	$(DUNE) build @fmt
 
 check:
@@ -31,13 +36,14 @@ check:
 package:
 	$(DUNE) subst
 	$(DUNE) install $(if ${DUNE_PACKAGES},--only-packages="${DUNE_PACKAGES}") --prefix=_install
-	if ! test -e Dockerfile; then echo "FROM alpine" > Dockerfile; fi
+	if ! test -e Dockerfile; then echo "FROM alpine:3.21.0" > Dockerfile; fi
 	sed '1aADD _install/ /usr/' Dockerfile > Dockerfile.package
 	docker buildx build --cache-to type=inline -f "Dockerfile.package" . -t "$(IMAGE):$$(git describe --always)"
+	echo "$(IMAGE):$$(git describe --always)"
 	docker push "$(IMAGE):$$(git describe --always)"
 	docker tag "$(IMAGE):$$(git describe --always)" "$(IMAGE):$$SLUG"
+	echo "$(IMAGE):$$SLUG"
 	docker push "$(IMAGE):$$SLUG"
-	echo "docker-image \"$(IMAGE):$$(git describe --always)\"" > metrics.txt
 
 package/clean:
 	docker rmi "$(IMAGE):$$(git describe --always)" "$(IMAGE):$$SLUG"
